version: '3.8'

services:
  db: # This is your MariaDB service definition
    image: mariadb:latest # Or a specific MariaDB version
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: esonero_db
      MYSQL_USER: vale
      MYSQL_PASSWORD: pw12
    ports:
      - "3306:3306" # Expose port for external access (optional, usually for debugging)
    volumes:
      - ./mariadb_data:/var/lib/mysql # Persist database data
      - ./mariadb_init:/docker-entrypoint-initdb.d # Mount the init directory
    container_name: db

  backend:
    build: ./backend
    ports:
      - "8003:8003"
    container_name: backend
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    ports:
      - "8001:8001"
    container_name: frontend
    depends_on:
      - backend
  
